routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

date_default_timezone_set('Asia/Kuala_Lumpur');

Route::get('/', 'HomeController@checksession');

Auth::routes();

Route::group(['middleware' => 'App\Http\Middleware\Admin'], function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController');
    Route::resource('profile', 'ProfileController');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::resource('carts', 'CartController');
    Route::get('/carts/add/{id}/{quantity}', 'CartController@add');
    Route::resource('sales', 'SaleController');
});

Route::group(['middleware' => 'App\Http\Middleware\User'], function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController', ['except' => 'edit', 'destroy']);
    Route::resource('profile', 'ProfileController', ['except' => 'edit', 'destroy']);
    Route::resource('categories', 'CategoryController',['except' => 'edit', 'destroy']);
    Route::resource('products', 'ProductController', ['except' => 'edit', 'destroy']);
    Route::resource('carts', 'CartController');
    Route::get('/carts/add/{id}/{quantity}', 'CartController@add');
    Route::resource('sales', 'SaleController', ['except' => 'edit', 'destroy']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdmin()
    {
        return $this->role === 'admin';
    }

    public function isSuper()
    {
        return $this->role === 'superadmin';
    }

    public function isSuperOrAdmin() 
    {
        return ($this->role === 'superadmin' || $this->role === 'admin');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'      => 'required|string|min:3',
            'email'     => 'required|string|email|max:255|unique:users',
            'role'      => 'required',
            'password'  => 'required|string|min:6',
            'confirm_password' => 'required|same:password',
        ]);

        $request['password'] = bcrypt($request->get('password'));
        User::create($request->all());

        return redirect()->route('users.index')->with('status','User successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        if($request->input('password') || $request->input('confirm_password')) {
            $rules = [
                'name'              => 'required|string|min:3',
                'email'             => 'required|string|email|max:255|unique:users,email,'.$user->id,
                'password'          => 'min:6',
                'confirm_password'  => 'same:password',
            ];
            $this->validate($request, $rules);
            $request['password'] = bcrypt($request['password']);
        } else {
            $rules = [
                'name'      => 'required|string|min:3',
                'email'     => 'required|string|email|max:255|unique:users,email,'.$user->id,
            ]; 
            $request['password'] = $user->password;
            $this->validate($request, $rules);
        }      
        
        $user->update($request->all());

        return redirect()->route('users.index', ['id' => $id])->with('status', 'Data Successfully Edited');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('users.index')->with('status', 'User successfully deleted');
    }
}

resources/views/users/create.blade.php
@extends('layouts.master')

@section('top')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <h3 style="margin-top:0px">Users</h3>
    <!-- general form elements -->
    <div class="box-header">
        <a href="{{ route('users.index') }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> BACK</a>
    </div>
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Create User</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="POST" action="{{ route('users.store')  }}" autocomplete="off">
            @csrf

            <div class="box-body">
                <div class="form-group">
                    <label>Name</label>
                    <input type="text" name="name" value="{{ old('name') }}" id="name" class="form-control" placeholder="Enter name" required>
                    @if ($errors->has('name'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('name') }}
                        </div>
                    @endif
                </div>

                <div class="form-group">
                    <label>Email Address</label>
                    <input type="email" name="email"  value="{{ old('email')  }}" id="email" class="form-control" placeholder="Enter email" required>
                    @if ($errors->has('email'))
                        <br>
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('email') }}
                        </div>
                    @endif
                </div>

                <div class="form-group">
                    <label>Role</label>
                    <select class="form-control select_role" value="{{ old('role')  }}" name="role" id="role" required>
                        <option value="">-- Select Role --</option>
                        <option value="admin" {{ (Input::old("role") == "admin" ? "selected":"") }}>Admin</option>
                        <option value="user" {{ (Input::old("role") == "user" ? "selected":"") }}>User</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Password</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                    @if ($errors->has('password'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('password') }}
                        </div>
                    @endif
                </div>

                <div class="form-group">
                    <label>Confirm Password</label>
                    <input type="password" name="confirm_password" id="confirm_password" class="form-control" placeholder="Confirm Password">
                    @if ($errors->has('confirm_password'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('confirm_password') }}
                        </div>
                    @endif
                </div>

            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> CREATE</button>
            </div>
        </form>
    </div>
    <!-- /.box -->
@endsection

@section('bot')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.full.min.js"></script>
<script type="text/javascript">
    $(".select_role").select2();
</script>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.master')

@section('top')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <h3 style="margin-top:0px">Users</h3>
    <!-- general form elements -->
    <div class="box-header">
        <a href="{{ route('users.index') }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> BACK</a>
    </div>
    @if ($user->role !== 'superadmin')
        <div class="box box-success box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">Edit User</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{{ route('users.update', ['id' => $user->id])  }}" autocomplete="off">
                @csrf
                @method('PATCH')

                <div class="box-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ $user->name }}" id="name" class="form-control" required>
                        @if ($errors->has('name'))
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('name') }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Email Address</label>
                        <input type="email" name="email"  value="{{ $user->email  }}" id="email" class="form-control"  required>
                        @if ($errors->has('email'))
                            <br>
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('email') }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Role</label>
                        <select class="form-control select_role" name="role" id="role" required>
                            <option value="admin" <?php if($user->role == 'admin') { echo 'selected'; } ?> >Admin</option>
                            <option value="user" <?php if($user->role == 'user') { echo 'selected'; } ?>>User</option> 
                        </select>
                    </div>

                    <div class="form-group">
                        <div class="alert alert-info" role="alert">
                            Leave the password field empty if you don't want to change.
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                        @if ($errors->has('password'))
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('password') }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Confirm Password</label>
                        <input type="password" name="confirm_password" id="confirm_password" class="form-control" placeholder="Confirm Password">
                        @if ($errors->has('confirm_password'))
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('confirm_password') }}
                            </div>
                        @endif
                    </div>

                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> UPDATE</button>
                </div>
            </form>
        </div>
        <!-- /.box -->
    @endif
@endsection

@section('bot')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.full.min.js"></script>
<script type="text/javascript">
    $(".select_role").select2();
</script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.master')

@section('top')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content')
    <h3 style="margin-top:0px">Users</h3>
    @if(session('status'))
        <div class="box-body">
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Success!</h4>
                {{ session('status') }}
            </div>
        </div>
    @endif

    <div class="box-header">
        <a href="{{ route('users.create') }}" class="btn btn-primary" ><i class="glyphicon glyphicon-plus"></i> Add User</a>
    </div>

    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">List of Users</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive">
            <table id="user-table" class="table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Last Sign In</th>
                        <th>Last Sign Out</th>
                        @if(Auth::user()->isSuperOrAdmin())
                            <th>Action</th>
                            <th>Delete</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td class="center"><div class="badge bg-green">{{ $user->role }}</div></td>
                            <td>{{ $user->sign_in_at }}</td>
                            <td>{{ $user->sign_out_at }}</td>
                            @if(Auth::user()->isSuperOrAdmin())
                                <td class="center">
                                    <a href="{{ route('users.show', [ 'id' => $user->id ]) }}" class="btn btn-info btn-sm custom"><i class="glyphicon glyphicon-eye-open"></i> VIEW </a>
                                    @if ($user->role !== 'superadmin')
                                        <a href="{{ route('users.edit', [ 'id' => $user->id ]) }}" class="btn btn-warning btn-sm custom"><i class="glyphicon glyphicon-edit"></i> EDIT </a>
                                    @else
                                        <a href="{{ route('users.edit', [ 'id' => $user->id ]) }}" class="btn btn-warning btn-sm custom disabled"><i class="glyphicon glyphicon-edit"></i> EDIT </a>
                                    @endif
                                </td>
                                @if($user->role !== 'admin' && $user->role !== 'superadmin')
                                    <td class="center">
                                        <form action="{{ route('users.destroy', [ 'id' => $user->id ])}}" method="post" onsubmit="return confirm('Delete username {{ $user->name }}, email {{ $user->email }} permanently?')" >
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger btn-sm" type="submit" ><i class="glyphicon glyphicon-trash"></i> DELETE</button>
                                        </form>
                                    </td>
                                @else
                                    <td class="center">
                                        <button class="btn btn-danger btn-sm disabled" type="submit" ><i class="glyphicon glyphicon-trash"></i> DELETE</button>
                                    </td>
                                @endif
                            @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection

@section('bot')
    <!-- DataTables -->
    <script src="{{ asset('assets/bower_components/datatables.net/js/jquery.dataTables.min.js') }} "></script>
    <script src="{{ asset('assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }} "></script>

    <script>
        $(function () {
            $('#user-table').DataTable()
        })

    </script>
@endsection

resources/views/users/show.blade.php
@extends('layouts.master')

@section('top')
@endsection

@section('content')
    <h3 style="margin-top:0px">Users</h3>
    <div class="box-header">
        <a href="{{ route('users.index') }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> BACK</a>
    </div>
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">View User</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive">
            <table class="table table-bordered table-striped datatable">
                <tr>
                    <th>ID</th>
                    <td>{{ $user->id }}</td>
                </tr>

                <tr>
                    <th>Name</th>
                    <td>{{ $user->name }}</td>
                </tr>

                <tr>
                    <th>Email</th>
                    <td>{{ $user->email }}</td>
                </tr>

                <tr>
                    <th>Role</th>
                    <td>{{ $user->role }}</td>
                </tr>

                <tr>
                    <th>Previous Sign In</th>
                    <td>{{ $user->sign_in_at }}</td>
                </tr>

                <tr>
                    <th>Previous Sign Out</th>
                    <td>{{ $user->sign_out_at }}</td>
                </tr>

                <tr>
                    <th>Created at</th>
                    <td>{{ $user->created_at }}</td>
                </tr>

                <tr>
                    <th>Updated at</th>
                    <td>{{ $user->updated_at }}</td>
                </tr>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection

@section('bot')
@endsection