routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

date_default_timezone_set('Asia/Kuala_Lumpur');

Route::get('/', 'HomeController@checksession');

Auth::routes();

Route::group(['middleware' => 'App\Http\Middleware\Admin'], function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController');
    Route::resource('profile', 'ProfileController');
    Route::resource('categories', 'CategoryController');
    Route::resource('products', 'ProductController');
    Route::resource('carts', 'CartController');
    Route::get('/carts/add/{id}/{quantity}', 'CartController@add');
    Route::resource('sales', 'SaleController');
});

Route::group(['middleware' => 'App\Http\Middleware\User'], function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('users', 'UserController', ['except' => 'edit', 'destroy']);
    Route::resource('profile', 'ProfileController', ['except' => 'edit', 'destroy']);
    Route::resource('categories', 'CategoryController',['except' => 'edit', 'destroy']);
    Route::resource('products', 'ProductController', ['except' => 'edit', 'destroy']);
    Route::resource('carts', 'CartController');
    Route::get('/carts/add/{id}/{quantity}', 'CartController@add');
    Route::resource('sales', 'SaleController', ['except' => 'edit', 'destroy']);
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['category_id','name','price','quantity','min_quantity','barcode','image'];

    protected $hidden = ['created_at','updated_at'];

    public function category()
    {
        return $this->belongsTo('App\Category', 'category_id', 'id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $category = Category::orderBy('name','ASC')
            ->get()
            ->pluck('name','id');

        return view('products.index', compact('products', 'category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'      => 'required|string|min:3|unique:products',
            'category_id'  => 'required',
            'price' => 'required',
            'quantity'     => 'required|integer',
            'min_quantity'     => 'required|integer',
            'barcode' => 'required|string|unique:products'
        ]);

        $input = $request->all();
        $input['image'] = null;

        if ($request->hasFile('image')){
            $input['image'] = '/upload/products/'.str_slug($input['name'], '-').'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('/upload/products/'), $input['image']);
        }

        Product::create($input);

        return redirect()->route('products.index')->with('status','Product successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        $category = Category::orderBy('name','ASC')
            ->get()
            ->pluck('name','id');

        return view('products.show', compact('product', 'category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $categories = Category::all();
        return view('products.edit',compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);

        $this->validate($request,[
            'name'      => 'required|string|min:3|unique:products,name,'.$product->id,
            'category_id'  => 'required',
            'price' => 'required',
            'quantity'     => 'required|integer',
            'min_quantity'     => 'required|integer',
            'barcode' => 'required|string|unique:products,barcode,'.$product->id,
        ]);

        $input = $request->all();
        $input['image'] = $product->image;

        if ($request->hasFile('image')){
            $input['image'] = '/upload/products/'.str_slug($input['name'], '-').'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('/upload/products/'), $input['image']);
        }

        $product->update($input);

        return redirect()->route('products.index')->with('status','Product successfully created');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        if (!$product->image == NULL){
            unlink(public_path($product->image));
        }
        $product->delete();
        return redirect()->route('products.index')->with('status', 'Product successfully deleted');
    }
}

resources/views/products/create.blade.php
@extends('layouts.master')

@section('top')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <h3 style="margin-top:0px">Products</h3>
    <!-- general form elements -->
    <div class="box-header">
        <a href="{{ route('products.index') }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> BACK</a>
    </div>
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Create Product</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="POST" action="{{ route('products.store')  }}" enctype="multipart/form-data" autocomplete="off">
            @csrf

            <div class="box-body">
                <div class="form-group">
                    <label>Name</label>
                    <input type="text" name="name" value="{{ old('name') }}" id="name" class="form-control" placeholder="Enter name" required>
                    @if ($errors->has('name'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('name') }}
                        </div>
                    @endif
                </div>

                <div class="form-group">
                    <label >Price</label>
                    <input type="number" class="form-control" id="price" name="price" step="0.01" required>
                </div>

                <div class="form-group">
                    <label >Quantity</label>
                    <input type="number" class="form-control" id="quantity" name="quantity" required>
                </div>

                <div class="form-group">
                    <label >Minimum Quantity</label>
                    <input type="number" class="form-control" id="min_quantity" name="min_quantity" required>
                </div>

                <div class="form-group">
                    <label>Category</label>
                    <select class="form-control select_category" value="{{ old('category_id')  }}" name="category_id" id="category_id" required>
                        {{-- <option value="">-- Select Category --</option> --}}
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label >Image</label>
                    <input type="file" id="image" name="image" >
                </div>

                <div class="form-group">
                    <label>Barcode</label>
                    <input type="text" name="barcode" value="{{ old('barcode') }}" id="barcode" class="form-control" placeholder="Enter barcode" required>
                    @if ($errors->has('barcode'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('barcode') }}
                        </div>
                    @endif
                </div>

            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> CREATE</button>
            </div>
        </form>
    </div>
    <!-- /.box -->
@endsection

@section('bot')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.full.min.js"></script>
<script type="text/javascript">
    $(".select_category").select2();
</script>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.master')

@section('top')
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
    <h3 style="margin-top:0px">Products</h3>
    <!-- general form elements -->
    <div class="box-header">
        <a href="{{ route('products.index') }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> BACK</a>
    </div>
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Update Product</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="POST" action="{{ route('products.update', ['id' => $product->id])  }}" enctype="multipart/form-data" autocomplete="off">
            @csrf
            @method('PATCH')

            <div class="box-body">
                <div class="form-group">
                    <label>Name</label>
                    <input type="text" name="name" value="{{ $product->name }}" id="name" class="form-control" placeholder="Enter name" required>
                    @if ($errors->has('name'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('name') }}
                        </div>
                    @endif
                </div>

                <div class="form-group">
                    <label >Price</label>
                    <input value="{{ $product->price }}" type="number" class="form-control" id="price" name="price" step="0.01" required>
                </div>

                <div class="form-group">
                    <label >Quantity</label>
                    <input value="{{ $product->quantity }}" type="number" class="form-control" id="quantity" name="quantity" required>
                </div>

                <div class="form-group">
                    <label >Minimum Quantity</label>
                    <input value="{{ $product->min_quantity }}" type="number" class="form-control" id="min_quantity" name="min_quantity" required>
                </div>

                <div class="form-group">
                    <label>Category</label>
                    <select class="form-control select_category" value="{{ $product->category }}" name="category_id" id="category_id" required>
                        {{-- <option value="">-- Select Category --</option> --}}
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label>Barcode</label>
                    <input type="text" name="barcode" value="{{ $product->barcode }}" id="barcode" class="form-control" placeholder="Enter barcode" required>
                    @if ($errors->has('barcode'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong><i class="icon fa fa-ban"></i> Alert!</strong> &nbsp; {{ $errors->first('barcode') }}
                        </div>
                    @endif
                </div>

                <div>
                    <label>Current Image</label>
                    <div>
                        <a href="{{ $product->image }}">
                            <img src="{{ $product->image }}" width="100" >
                        </a>
                    </div>
                </div>

                <div class="form-group">
                    <br>
                    <div class="alert alert-info" role="alert">
                        Leave the change image section below empty if you don't want to change.
                    </div>
                    </div>
                <div class="form-group">
                    <label >Change Image</label>
                    <input type="file" id="image" name="image" >
                </div>

            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> UPDATE</button>
            </div>
        </form>
    </div>
    <!-- /.box -->
@endsection

@section('bot')
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.full.min.js"></script>
<script type="text/javascript">
    $(".select_category").select2();
</script>
@endsection

resources/views/products/index.blade.php
@extends('layouts.master')

@section('top')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('assets/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content')
    <h3 style="margin-top:0px">Products</h3>
    @if(session('status'))
        <div class="box-body">
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Success!</h4>
                {{ session('status') }}
            </div>
        </div>
    @endif

    <div class="box-header">
        <a href="{{ route('products.create') }}" class="btn btn-primary" ><i class="glyphicon glyphicon-plus"></i> Add Product</a>
    </div>

    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">List of Products</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive">
            <table id="product-table" class="table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Min</th>
                        <th>Category</th>
                        <th>Barcode</th>
                        <th>Image</th>
                        @if(Auth::user()->isSuperOrAdmin())
                            <th>Action</th>
                            <th>Delete</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>{{ $product->id }}</td>
                            <td>{{ $product->name }}</td>
                            <td>EM {{ $product->price }}</td>
                            <td>{{ $product->quantity }}</td>
                            <td>{{ $product->min_quantity }}</td>
                            <td>{{ $product->category->name }}</td>
                            <td>{{ $product->barcode }}</td>
                            <td>
                                @if($product->image)
                                    <a href="{{ $product->image }}">
                                        <img src="{{ $product->image }}" width="50" >
                                    </a>
                                @endif
                            </td>
                            @if(Auth::user()->isSuperOrAdmin())
                                <td class="center">
                                    <a href="{{ route('products.show', [ 'id' => $product->id ]) }}" class="btn btn-info btn-sm custom"><i class="glyphicon glyphicon-eye-open"></i> VIEW</a>
                                    <a href="{{ route('products.edit', [ 'id' => $product->id ]) }}" class="btn btn-warning btn-sm custom"><i class="glyphicon glyphicon-edit"></i> EDIT</a>
                                </td>
                                <td class="center">
                                    <form action="{{ route('products.destroy', [ 'id' => $product->id ])}}" method="post" onsubmit="return confirm('Delete product {{ $product->name }} permanently?')" >
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-sm" type="submit" ><i class="glyphicon glyphicon-trash"></i> DELETE</button>
                                    </form>
                                </td>
                            @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection

@section('bot')
    <!-- DataTables -->
    <script src="{{ asset('assets/bower_components/datatables.net/js/jquery.dataTables.min.js') }} "></script>
    <script src="{{ asset('assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }} "></script>

    <script>
        $(function () {
            $('#product-table').DataTable()
        })

    </script>
@endsection

resources/views/products/show.blade.php
@extends('layouts.master')

@section('top')
@endsection

@section('content')
    <h3 style="margin-top:0px">Products</h3>
    <div class="box-header">
        <a href="{{ route('products.index') }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> BACK</a>
    </div>
    <div class="box box-success box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">View Product</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive">
            <table class="table table-bordered table-striped datatable">
                <tr>
                    <th>ID</th>
                    <td>{{ $product->id }}</td>
                </tr>

                <tr>
                    <th>Name</th>
                    <td>{{ $product->name }}</td>
                </tr>

                <tr>
                    <th>Price</th>
                    <td>{{ $product->price }}</td>
                </tr>

                <tr>
                    <th>Quantity</th>
                    <td>{{ $product->quantity }}</td>
                </tr>

                <tr>
                    <th>Minimum Quantity</th>
                    <td>{{ $product->min_quantity }}</td>
                </tr>

                <tr>
                    <th>Category</th>
                    <td>{{ $product->category->name }}</td>
                </tr>

                <tr>
                    <th>Barcode</th>
                    <td>{{ $product->barcode }}</td>
                </tr>

                <tr>
                    <th>Image</th>
                    <td>
                        <a href="{{ $product->image }}">
                            <img src="{{ $product->image }}" width="100" >
                        </a>
                    </td>
                </tr>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection

@section('bot')
@endsection